tls:
    options:
        default:
            minVersion: "VersionTLS12"
    certificates:
        - certFile: {{ env "SSL_CERT_CHAIN_PATH" }}
          keyFile: {{ env "SSL_PRIVATE_KEY_PATH" }}
    stores:
        default:
            defaultCertificate:
                certFile: {{ env "SSL_CERT_CHAIN_PATH" }}
                keyFile: {{ env "SSL_PRIVATE_KEY_PATH" }}

http:
    routers:
        dashboard:
            entryPoints:
                - "https"
            rule: Host(`{{ env "TRAEFIK_DOMAIN" }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
            service: api@internal
            middlewares:
                #- "keycloak"
            tls: {}

    middlewares:
        keycloak:
            forwardAuth:
                authResponseHeaders:
                    - "X-Forwarded-User"
