global:
  checkNewVersion: true
  sendAnonymousUsage: true
entryPoints:
  https:
    address: :443
    http:
      tls: {}
providers:
  docker:
    watch: true
    defaultRule: "Host(`{{ normalize .Name }}.{{ .Env.TRAEFIK_DOMAIN }}`)"
    exposedByDefault: false 
  file:
    filename: /etc/traefik/traefik_dynamic.yml
api:
  insecure: false # if true, will expose api on https port 8080
  dashboard: true
  debug: false
ping:
  entryPoint: "https"
